enum class Catalog(internal val number: Int, internal val status: Status) {
    FindAllOdds(0, Status.Accepted),
    TwoSum(1, Status.Accepted),
    AddTwoNumbers(2, Status.Accepted),
    LongestSubstringWithoutRepeatingCharacters(3, Status.Accepted),
    LongestPalindromicSubstring(5, Status.Accepted),
    ZigZagConversion(6, Status.Accepted),
    ReverseInteger(7, Status.Accepted),
    PalindromeNumber(9, Status.Accepted),
    RegularExpressionMatching(10, Status.Accepted),
    ContainerWithMostWater(11, Status.Accepted),
    LongestCommonPrefix(14, Status.Accepted),
    ThreeSum(15, Status.Accepted),
    LetterCombinationsOfAPhoneNumber(17, Status.Accepted),
    RemoveNthNodeFromEndOfList(19, Status.Accepted),
    ValidParentheses(20, Status.Accepted),
    MergeTwoSortedLists(21, Status.Accepted),
    GenerateParentheses(22, Status.Accepted),
    MergeKSortedLists(23, Status.Accepted),
    SwapNodesInPairs(24, Status.Accepted),
    ReverseNodesInKGroup(25, Status.Accepted),
    RemoveDuplicatesFromSortedArray(26, Status.Accepted),
    RemoveElement(27, Status.Accepted),
    ImplementStrStr(28, Status.Accepted),
    DivideTwoIntegers(29, Status.Accepted),
    NextPermutation(31, Status.Accepted),
    SearchInRotatedSortedArray(33, Status.Accepted),
    SearchForARange(34, Status.Accepted),
    SearchInsertPosition(35, Status.Accepted),
    ValidSudoku(36, Status.Accepted),
    SudokuSolver(37, Status.Accepted),
    CombinationSum(39, Status.Accepted),
    CombinationSum2(40, Status.Accepted),
    FirstMissingPositive(41, Status.Accepted),
    TrappingRainWater(41, Status.Accepted),
    ;

}
